### PR TITLE
Client: Fix #444: Don't error if there is no `this`

### LINKED ISSUE #444: Can't successfully load client with WebPack+babel
**Version:** 5.0.0

**Environment:**
  - **Operating system:** Windows 10, 64bit
  - **Browser:** Chrome 48.0.2564.116 m
  - **Node.js:** 5.4.0

**Expected result:** client imported successfully in browser

**Actual result:** webpack mutates "this" to "undefined" on line 8 of client (`})("Primus", this, function wrapper() {`), resulting in: Uncaught TypeError: Cannot set property 'Primus' of undefined

**Steps to reproduce:**
1. generate 'websocket' client
2. require the client: `const Primus = require('../api/primus');`
3. use webpack (with babel) to generate bundle
4. open page referencing bundle

### PR DESCRIPTION
**Pull request by marcelklehr**
if this is the case, a module loader is responsible, so we
don't care about exposing a global anyway

### CODE REVIEW

**Comment by lpinca** [comment]
Awesome, LGTM. Thank you!

**Comment by lpinca** [comment]
Let's wait for @3rd-Eden review before merge.

File: index.js [hunk 1]
```diff
@@ -591,16 +594,17 @@ Primus.readable('library', function compile(nodejs) {
...
-      '(function libraryWrap(Primus) {',
+      'function (Primus) {',
       library,
-      '})(this["'+ global +'"]);',
-      ''
+      '}'
     ].join('\n');
-  })).join('\n');
+  }).join(',\n'))
+  .concat([']);'])
```
Comment (lpinca) [inline index.js]: @marcelklehr We can use the string directly here, without the array.

Comment (marcelklehr) [inline index.js]: Wut? Sure enough. I didn't know that :)

**Comment by marcelklehr** [comment]
done.

**Comment by 3rd-Eden** [comment]
LGTM

**Comment by marcelklehr** [comment]
When are you planning the next release?

**Comment by lpinca** [comment]
I wanted to wait proper SSL support in uws, but I guess we can cut a release now, and update uws (if needed) later.

If there are no objections I'll release primus@5.2.0 later today.
